services:
    portfolio:
        image: portfolio_react
        restart: always
        container_name: portfolio
        ports:
            - 8000:80
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/var/www/html